name: Auto Commit

on:
  workflow_dispatch:
  schedule:
    - cron: "*/1 * * * *"

jobs:
  update_readme:
   name: "Update user Readme repo"
   runs-on: ubuntu-latest
   steps:
     - name: Checkout code
       uses: actions/checkout@v4
      # Add or replace dependency steps here
     - name: Install Ruby and gems
       uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
       with:
         bundler-cache: true 
     - name: Set up database schema
       run: bundle exec rake run
